import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsLearn: SidebarsConfig = {
  learnSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsLearn;
