import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: 'documentation'}],
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
};

export default sidebars;